rwth-i6/pytorch-to-returnn

pytorch_to_returnn/torch/nn/modules/__init__.py, pytorch_to_returnn/torch/nn/modules/container.py
Add `ModuleList` class to the torch container modules. Analogous to `Sequential`.
=> Add ModuleList

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/activation.py
Add existing RETURNN activations. For `Abs`, also add `torch.tensor.abs`.
=> add GELU and abs activation

pytorch_to_returnn/torch/__init__.py, pytorch_to_returnn/torch/tensor.py
Add `LongTensor`. Not sure if we need more than that.
=> add LongTensor

pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
Extend slicing of tensors to support slicing with start, stop and end on tensors with on or multiple dimensions.
=> extend slicing of tensors

pytorch_to_returnn/torch/nn/modules/conv.py, tests/test_layers.py
Default parameter shapes were still 1D
=> fix of default parameters in ConvTranspose2d

pytorch_to_returnn/torch/__init__.py, pytorch_to_returnn/torch/autograd/__init__.py, pytorch_to_returnn/torch/jit.py, pytorch_to_returnn/torch/nn/modules/__init__.py, pytorch_to_returnn/torch/nn/modules/loss.py, pytorch_to_returnn/torch/onnx/__init__.py, pytorch_to_returnn/torch/serialization.py, pytorch_to_returnn/torch/utils/data/__init__.py, pytorch_to_returnn/torch/utils/data/dataloader.py, pytorch_to_returnn/torch/utils/data/dataset.py
Add some dummy classes and functions to avoid import errors for the wav2vec model.
=> Dummies to avoid import errors

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
Add `tensor.expand`. To do this, first reshape to get additional axes if necessary and then use RETURNN's `TileLayer` to expand to larger size.
=> add tensor.expand

pytorch_to_returnn/torch/tensor.py
Add more tensor ops, namely `tensor.flatten()` and `tensor.resize()` (currently really minimal).
=> Add more tensor ops

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/tensor.py
Add tensor greater equal op. Other comparisons can be added analogously.
=> add tensor greater equal op

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/normalization.py, tests/test_layers.py
Add PyTorch's group norm using `NormLayer` in RETURNN.
=> add group norm

pytorch_to_returnn/converter/converter.py, pytorch_to_returnn/torch/nn/modules/module.py, pytorch_to_returnn/torch/nn/modules/operator.py, tests/test_layers.py
I added a test case of an operation that works in PyTorch but currently does not work here.
=> broadcasting with different axes types

pytorch_to_returnn/torch/nn/modules/operator.py, tests/test_layers.py
Hi @albertz, in the context of #28 I figured that adding a bias which has only feature dim using broadcasting is not yet supported, see test case. What do you think how this should be done?
=> add bias broadcasting test case

pytorch_to_returnn/torch/jit.py
add `torch.jit._unwrap_optional`
=> add torch.jit._unwrap_optional

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/linear.py, pytorch_to_returnn/torch/nn/modules/module.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
Add `torch.nn.functional.linear` using the new module `FunctionalLinear`. This first needs the corresponding PR in returnn https://github.com/rwth-i6/returnn/pull/416
=> add linear functional

pytorch_to_returnn/torch/nn/functional.py, tests/test_layers.py
Add batch matix-matrix product `torch.bmm` using existing `matmul`.
=> add torch.bmm

pytorch_to_returnn/torch/_C.py
=> add torch.empty()

pytorch_to_returnn/converter/converter.py
In #43, there is a failing test case because one test accesses the variable with the same name but a different shape of another test. This PR fixes this by using separate sessions with separate graphs as done in the RETURNN tests.
=> make scope for separate sessions

pytorch_to_returnn/converter/converter.py, pytorch_to_returnn/import_wrapper/base_wrappers/class_.py, pytorch_to_returnn/import_wrapper/wrap.py, pytorch_to_returnn/naming/call.py, pytorch_to_returnn/torch/_C.py, pytorch_to_returnn/torch/nn/modules/module.py, pytorch_to_returnn/torch/nn/modules/rnn.py, pytorch_to_returnn/torch/nn/modules/shape.py, pytorch_to_returnn/torch/nn/utils/__init__.py, pytorch_to_returnn/torch/nn/utils/rnn.py, tests/test_layers.py
For an example from padertorch that I'd like to import, we need support for `PackedSequence`. I implemented a first version of what we discussed and would appreciate your feedback on it, @albertz :)
=> Add support for PackedSequences

pytorch_to_returnn/torch/tensor.py
=> allow slicing with tuples including ints

pytorch_to_returnn/torch/nn/modules/rnn.py, pytorch_to_returnn/torch/nn/modules/shape.py, pytorch_to_returnn/torch/nn/utils/rnn.py, tests/test_layers.py
Small fix following up on #71.
=> fix batch_first in pack_sequence

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
Use RETURNN's `ReduceLayer` to add `torch.sum` and `Tensor.sum`.
=> add torch.sum and Tensor.sum

pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
I would like to allow gather a tensor with another tensor which contains integer indices which the `GatherLayer` should already support.
=> allow gathering with tensors

pytorch_to_returnn/torch/nn/modules/module.py
Copied from https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py
=> add Module.modules

pytorch_to_returnn/naming/naming.py, pytorch_to_returnn/naming/tensor.py, pytorch_to_returnn/torch/_C.py, pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/module.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/nn/modules/shape.py, pytorch_to_returnn/torch/nn/modules/variable.py, pytorch_to_returnn/torch/nn/utils/rnn.py, pytorch_to_returnn/torch/tensor.py, tests/test_layers.py
For fixing #84, as demonstrated in #85, we need to save more information in `SizeValue`.
=> SizeValue generic support for dynamic sizes

pytorch_to_returnn/converter/converter.py, pytorch_to_returnn/import_wrapper/torch_wrappers/module.py, pytorch_to_returnn/naming/call.py, pytorch_to_returnn/naming/module.py, pytorch_to_returnn/naming/namespace.py, pytorch_to_returnn/naming/naming.py, pytorch_to_returnn/torch/_C.py, pytorch_to_returnn/torch/nn/modules/module.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/nn/modules/shape.py, pytorch_to_returnn/torch/nn/modules/variable.py, tests/test_layers.py
Add a test case which demonstrates the issue #84.
=> indexing merged dim

pytorch_to_returnn/torch/nn/functional.py, pytorch_to_returnn/torch/nn/modules/shape.py, pytorch_to_returnn/torch/nn/modules/variable.py, tests/test_layers.py
=> Fix new_zeros for dynamic size

pytorch_to_returnn/torch/nn/modules/variable.py
Just a small comment for clarification on `FullStatic`.
=> FullStatic: docstring for clarification

tests/test_layers.py
The issue described in #94 is visible in the test case added here.
=> Add unsqueeze test case

tests/test_layers.py
I add a test case here which demonstrates the issue described in #96.
=> Test merge batch with modified time dim

tests/test_layers.py
I add a test case here which demonstrates the issue described in #100.
=> Test adding randint and arange

tests/test_layers.py
=> Fix floordiv for SizeValue

pytorch_to_returnn/converter/utils.py, pytorch_to_returnn/torch/nn/modules/operator.py, tests/test_layers.py
Adds the test which reproduces the issue described in #111.
=> Dummy run with serialized dim tags

pytorch_to_returnn/naming/tensor.py, pytorch_to_returnn/torch/nn/modules/operator.py, pytorch_to_returnn/torch/nn/modules/variable.py, tests/test_layers.py
=> Output dim tag of torch.full

pytorch_to_returnn/torch/nn/modules/padding.py
In `GenericPadNd`, the axes are currently converted to RETURNN manually before passing them to `self._get_input_axis_to_returnn`, however, `self._get_input_axis_to_returnn` should receive the torch axes. This is fixed here, which also simplifies the code a bit.
=> fix for axes in GenericPadNd

pytorch_to_returnn/converter/converter.py
`verify_torch_and_convert_to_returnn` is the main entry point for the converter, however, it is not possible to set the `validate_allclose_kwargs` used in `Naming` from there. I added an option in `Converter` to allow this.
=> allow setting Naming.validate_allclose_kwargs

pytorch_to_returnn/torch/nn/modules/conv.py
`_FunctionalConvNd` is missing a `_get_output_shape_from_returnn()` method. It is very similar to the one of `_ConvNd`.
=> add _FunctionalConvNd._get_output_shape_from_returnn
