rwth-i6/pytorch-to-returnn

- pytorch_to_returnn/torch/nn/modules/conv.py
Add `ConvTranspose2d` class to the torch conv modules. Analogous to `ConvTranspose1d`.
> Add ConvTranspose2d

- pytorch_to_returnn/converter/README.md
- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/import_wrapper/torch_wrappers/tensor.py
- pytorch_to_returnn/naming/naming.py
- pytorch_to_returnn/torch/nn/modules/container.py
- pytorch_to_returnn/torch/tensor.py
These are some really small changes.
- The numpy random seed should be reset before each run just like the PyTorch random seed.
- `tensor.new` behaves different from `tensor.new_empty` when a tensor is passed as argument. I adapted that.
- Fix of small naming problem for the case that the root module contains parameters.
- One import was missing for the code of `ModuleList`.
- Added `FloatTensor` and fixed the args of `LongTensor`.
> Small fixes

- pytorch_to_returnn/torch/nn/init.py
- pytorch_to_returnn/torch/tensor.py
Add `kaiming_normal_` and `constant_`.
Also, `torch.Tensor.uniform_()` and related should have a return value, e.g. I encountered a statement 
`self.mask_emb = nn.Parameter(torch.FloatTensor(args.encoder_embed_dim).uniform_())`
which does not work if there is no return value.
> fix and extend tensor initializers

- pytorch_to_returnn/torch/tensor.py
Currently it is possible to do something like `x.view(1, -1)` but in PyTorch you can also do `x.view(some_shape)` with `some_shape=(1, -1)`.
> allow tuple as input to tensor.view and expand

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/naming/call.py
- pytorch_to_returnn/naming/naming.py
- pytorch_to_returnn/torch/nn/modules/module.py
- pytorch_to_returnn/torch/nn/modules/variable.py
- tests/test_layers.py
Currently, `Module.forward` is not supported when using kwargs as shown in the test cast. This draft PR is meant to fix this.
> enable forward with kwargs

- pytorch_to_returnn/torch/nn/functional.py
Add dropout functional to support a statement like `x = F.dropout(x)`.
> add dropout functional

- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/activation.py
- pytorch_to_returnn/torch/tensor.py
Specifically, `tensor.clone` and `tensor.device` which are ignored here as well as `tensor.pow`. Not sure if there is a more elegant way for `pow` than the `EvalLayer` but this seems pretty straight-forward.
> add more tensor operations

- pytorch_to_returnn/torch/__init__.py
- pytorch_to_returnn/torch/cuda.py
- pytorch_to_returnn/torch/jit.py
- pytorch_to_returnn/torch/nn/modules/module.py
I encountered some things like `torch.jit.is_scripting()`, `torch.cuda.is_available()` and `self.training` on a `Module` which I am currently just ignoring. What do you think about these?
> meta infos

- pytorch_to_returnn/naming/call.py
- pytorch_to_returnn/naming/namespace.py
- pytorch_to_returnn/torch/nn/modules/module.py
- tests/test_layers.py
I slightly modified the `Fp32GroupNorm` test case to reproduce the problem that I mentioned earlier in #18. If `Fp32GroupNorm` is wrapped inside a `Sequential`, the layer that is input to `GroupNorm.import_params_torch_to_returnn` will be a `SubnetworkLayer`. Do you have any ideas on this?
> subnetwork problem in group norm

- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- tests/test_layers.py
In case concatenation of tensors happens in the feature dimension we can take advantage of the fact that the RETURNN copy layer concatenates it's inputs in the feature dimension.
> Add torch.cat for the case that concatenation happens in the feature dim

- pytorch_to_returnn/torch/nn/functional.py
- tests/test_layers.py
Generalize `reshape` to allow reshapes of `(..., a*b, c,...) -> (..., a, b*c,...)` or `(..., a, b*c,...) -> (..., a*b, c,...)`.
> allow more general reshapes

- pytorch_to_returnn/torch/nn/modules/linear.py
- tests/test_layers.py
I added a test for the case of multiple shared remaining axes which failed. To fix it, I added `Matmul._get_output_shape_from_returnn`. Additionally, in `Matmul.create_returnn_layer_dict`, `var1` and `var2` should be created by inserting at the beginning of the list, not by appending. Otherwise, the output order in returnn is reversed.
> fix matmul

- pytorch_to_returnn/naming/tensor.py
- pytorch_to_returnn/torch/nn/modules/module.py
- tests/test_layers.py
Having tensors where multiple axes have the same dim tag lead to problems in `_get_input_axis_to_returnn` as well as when creating `out_returnn_axis_to_torch_axis` in `_base_get_output_shape_from_returnn`. Using the new dim tag format `stag-single:<idx>:<name>` for spatial axes in returnn (see https://github.com/rwth-i6/returnn/pull/490), we can circumvent this.
> fix for spatial axes with same dim tag

- pytorch_to_returnn/torch/nn/modules/shape.py
- tests/test_layers.py
When merging dims, the `MergeDimsLayer` target axis depends on whether the input feature dim axis is included in the merged dims or not. This was not covered in `MergeDims.generic_get_output_shape_from_returnn`. In case the feature dim axis was included in the merged dims and the merged dims were not adjacent, this leads to problems which this PR fixes.
> fix for merge dims

- pytorch_to_returnn/naming/naming.py
- pytorch_to_returnn/torch/nn/modules/variable.py
- tests/test_layers.py
Loading the params to returnn works correctly when having a module `mod = torch.nn.Linear(n_in, n_out)` and calling it directly, i.e., `y = mod(x)`. However, if the params are used directly like `mod.weight`, they are not loaded in returnn currently.
> fix loading params to returnn

- pytorch_to_returnn/torch/nn/functional.py
- tests/test_layers.py
Adds `F.multi_head_attention_forward` and a test case which is a simplified version of the `MultiheadAttention` module in fairseq.
> add F.multi_head_attention_forward

- pytorch_to_returnn/torch/nn/modules/padding.py
- tests/test_layers.py
The current implementation of F.pad fails when the padding tuple has more than 2 entries, because RETURNN expects the padding to be split up by axes.
> Fix F.pad in case the padding happens in multiple dimensions

- pytorch_to_returnn/torch/nn/modules/module.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- pytorch_to_returnn/torch/nn/modules/padding.py
- tests/test_layers.py
In #41 we introduced asserting the correct torch shape of tensor entries. There are multiple modules which have issues here. This PR fixes this by adding `_get_output_shape_from_returnn` for a number of modules.
> fix torch shape for multiple modules

- pytorch_to_returnn/torch/tensor.py
`tensor.ndimension()` is an alias for `tensor.dim()`, see https://pytorch.org/docs/stable/generated/torch.Tensor.ndimension.html
> add tensor.ndimension()

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/torch/nn/init.py
- pytorch_to_returnn/torch/nn/modules/module.py
- tests/test_layers.py
The returnn dummy input uses arbitrary sizes for the dynamic axes. I had a case where the size of the time dim was reduced by convolutions such that the chosen arbitrary size was too small (see added test case). For such situations, I added the option `returnn_dummy_input_shape` for the `Converter` so that the dummy input shape can be manually set.
> allow setting shape for returnn dummy input

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/torch/nn/modules/module.py
Update the usage if `size_placeholder` since it was changed in RETURNN in https://github.com/rwth-i6/returnn/commit/6283b2d367c68f029bef221e5edf12d4abeb95b8.
> fix usage of size_placeholder

- tests/test_layers.py
I am running into trouble when using unsqueeze together with transposed convolution after the changes for the explicit data dimension tags. I  dont really know what the problem is though. I added a test case which should reproduce the problem.
The error is given by:
```
File "/u/dierkes/pytorch-to-returnn-projects/pytorch-to-returnn-fork/pytorch-to-returnn/tests/returnn/returnn/tf/util/data.py", line 178, in DimensionTag.set_tag_on_size_
tensor
line: assert x._is_size_of_dim_tag in (None, self)
locals:
x = <local> <tf.Tensor 'extern_data/placeholders/data/data_dim1_size:0' shape=(?,) dtype=int32>
x._is_size_of_dim_tag = <local> DimensionTag{'time:var:extern_data:data'[B]}
self = <local> DimensionTag{'ConvTranspose2d_spatial0_transposed_conv'[?]}
AssertionError
```
> added test for using unsqueeze together with transposed convolution

- pytorch_to_returnn/torch/__init__.py
- pytorch_to_returnn/torch/distributions.py
- pytorch_to_returnn/torch/nn/__init__.py
- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/activation.py
- pytorch_to_returnn/torch/nn/parallel.py
- pytorch_to_returnn/torch/optim/__init__.py
- pytorch_to_returnn/torch/optim/lr_scheduler.py
- pytorch_to_returnn/torch/tensor.py
Add dummies to avoid import errors. For `torch.__version__`, I used 1.8.1 because that is currently used in the tests here.
> add dummies to avoid import errors

- pytorch_to_returnn/naming/naming.py
If a `Module` is called in the code that should be converted, we go through `Naming.push_module_call` already in `_run_traced_orig_torch()`. There we obtain `entry.inputs_flat = [self._make_tensor(x) for x in inputs_flat]`. Since the tensors are not registered there, we get `None`s there. This can potentially lead to errors in the subsequend nesting. As `entry.inputs_args` and `entry.inputs_kwargs` are not used in `_run_traced_orig_torch()`, we can avoid the nesting in this case.
> Naming.push_module_call: fix for unregist. tensors

- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- pytorch_to_returnn/torch/tensor.py
- tests/test_layers.py
Add `torch.nn.functional.permute` and `Tensor.permute` which uses the previous one. In order to do this, I also fixed `out_returnn_axis_from_torch_axis` for `Transpose`. Apparently, we only had cases where two axes were transposed, not where a more complicated transpose was done like 0->1, 1->2, 2->0, so the error did not become obvious before.
> Add permute

- pytorch_to_returnn/converter/converter.py
So far, we had no batch-time-major case, but there I think we need the following fix when ignoring entries that are beyond the sequence lengths.
> fix when using input seq lens

- pytorch_to_returnn/torch/nn/modules/operator.py
- tests/test_layers.py
Rebase `torch.cat` to use RETURNN's `ConcatLayer`, which makes it more flexible. In particular, also other dims than feature can now be concatenated.
> rebase and extend torch.cat

- pytorch_to_returnn/torch/nn/modules/shape.py
- tests/test_layers.py
The `elif` branch that I edited is supposed to be the case where `i` refers to a dim which outside (larger than) the unflattened dims. Equality should also be contained in this case.
> fix Unflatten out_returnn_axis_from_torch_axis

- pytorch_to_returnn/torch/tensor.py
- tests/test_layers.py
`x[None]` is the same as `x.unsqueeze(0)`.
> allow indexing tensor with none

- pytorch_to_returnn/torch/nn/modules/shape.py
- tests/test_layers.py
As mentioned in #85, the `FlattenBatchLayer` should not be used in `MergeDims`.
> do not use FlattenBatchLayer in MergeDims

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/import_wrapper/context.py
- pytorch_to_returnn/import_wrapper/torch_wrappers/__init__.py
- pytorch_to_returnn/import_wrapper/torch_wrappers/function.py
- pytorch_to_returnn/import_wrapper/wrap.py
- pytorch_to_returnn/naming/call.py
- pytorch_to_returnn/naming/naming.py
- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/module.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- tests/test_layers.py
As described in #89, we currently do not account for non-deterministic modules when checking against the reference.
I would like to add `torch.randint`, therefore this PR should also introduce a logic for non-deterministic modules
> Checks for non-deterministic modules

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/naming/returnn_ctx.py
- pytorch_to_returnn/naming/tensor.py
- pytorch_to_returnn/torch/nn/modules/batchnorm.py
- pytorch_to_returnn/torch/nn/modules/conv.py
- pytorch_to_returnn/torch/nn/modules/pooling.py
- tests/test_layers.py
For #92, we need RETURNN's `behavior_version` to have the correct behavior of the `DotLayer`. There might be fixes necessary due to this change.
> add RETURNN behavior_version

- pytorch_to_returnn/import_wrapper/context.py
- pytorch_to_returnn/naming/naming.py
- pytorch_to_returnn/naming/tensor.py
- pytorch_to_returnn/torch/_C.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- pytorch_to_returnn/torch/nn/modules/shape.py
- tests/test_layers.py
So far, we only supported `torch.randint` for integer inputs. In this PR, this should be extended to dynamic inputs.
> randint: allow dynamic inputs

- pytorch_to_returnn/torch/nn/modules/operator.py
- tests/test_layers.py
In `Range._get_output_shape_from_returnn`, if `limit` is a `Tensor` we currently set the `dim_tag` for the `SizeValue` in `torch_shape`, but not the `originating_tensor`. This might be problematic as can be seen in the testcase that I added
> fix Range._get_output_shape_from_returnn

- pytorch_to_returnn/torch/_C.py
- pytorch_to_returnn/torch/nn/modules/operator.py
- pytorch_to_returnn/torch/nn/modules/shape.py
- pytorch_to_returnn/torch/nn/modules/variable.py
- tests/test_layers.py
I added a testcase for negative sampling. Currently, there is an issue in the final concatenation (`torch.cat`) of the input with the negative samples. Namely, in `ConcatLayer`'s `_copy_compatible`, an additional axis is created which should not be the case and that results in an error. The problem, however, may already be in `torch.randint` where the RETURNN output is `(B,F)` although it is created with `(B,T)` dim tags.
I'll post the stack trace once the CI tests are finished.
> Negative sampling demo

- pytorch_to_returnn/naming/call.py
- tests/test_layers.py
I have a case where the output of a module is not a tensor. A simple example could be:
```
class DummyModule(torch.nn.Module):
def forward(self, y):
return {"a": 1, "b": y + 1}
```
I'm not exactly sure about all the logic in `CallEntry`, but just focusing on the `Tensor` outputs seems to work here.
> Non-tensor module outputs

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/converter/utils.py
I added `Converter.get_returnn_config_serialized` which allows to get a serialized string containing `extern_data` and the `network` dict from the `Converter`. The serialization is copied from [returnn_common](https://github.com/rwth-i6/returnn_common/blob/main/nn/naming.py), there are just two small adjustments regarding `Size` inputs and `floordiv` (see separate commit which can be squashed later).
An example usage would be
```
converter = verify_torch_and_convert_to_returnn(...)
with open(...) as f:
f.write(converter.get_returnn_config_serialized())
```
> allow writing serialized config

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/converter/utils.py
- tests/returnn_helpers.py
- tests/test_layers.py
The serialization should get the `int` value of a `SizeValue`, otherwise we'll have something in the output network like `'shape': ('static_dim'(768)(768),)` which will obviously lead to an error.
> fix serialization for SizeValues

- pytorch_to_returnn/converter/converter.py
- pytorch_to_returnn/torch/__init__.py
- pytorch_to_returnn/torch/nn/functional.py
- pytorch_to_returnn/torch/nn/modules/activation.py
- pytorch_to_returnn/torch/tensor.py
- tests/test_layers.py
I added `torch.nn.functional.cross_entropy` and some small things that were necessary for that. It is used in the contrastive loss of wav2vec. I added an analogous usage in `test_contrastive_loss` which is not yet working fully.
> Add cross entropy

- pytorch_to_returnn/torch/nn/modules/conv.py
- tests/test_layers.py
Allow using groups for `_FunctionalConvNd`. I also added a test for depthwise convolution with stride 2. This revealed some problems on RETURNN side. It should work with https://github.com/rwth-i6/returnn/pull/1227.
> allow functional depthwise conv

- pytorch_to_returnn/naming/call.py
- pytorch_to_returnn/torch/nn/modules/module.py
- tests/test_layers.py
I'd like to create a module which has a torch forward function, but nevertheless is mapped to a custom RETURNN layer call. The basic idea is to have something like
```
class MyModule(torch.nn.Module):
is_original_torch_module = False
def forward(self, x):
y = foo(x)
return y
def create_returnn_layer_dict(self, input):
return {"class": "<some_layer>", "from": self._get_input_layer_name(input)}
```
Right now, the custom `create_returnn_layer_dict` is ignored and the code inside `forward` is wrapped. This PR changes this behavior to make sure to use the custom `create_returnn_layer_dict`.
> allow custom modules with custom RETURNN layer
